### ISSUE TITLE
[TODO] Hikari Connection Pool

### ISSUE THREAD

**Issue by HandsomeRomanian** [Ultracrepidarianism/Kingdom#3]
We are never checking the status or the stability of the connection. 
The plugin takes for granted the fact that the connection is up and good to go. 

I believe a system should be put in place where in the scenario of a failure on connection or after connection a fallback storage should be used to ensure reliability and once connection is restored data is synced with main storage. 
If case of fallback failure plugin should not load. 
 

[Idea] Add a secret extreme option to the confirmation where plugin will stop the server or something really anoying like that in case of failure.

**Comment by DeveloperAnonymous** [comment]
Not our problem, they should properly setup their DB
